In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_csv('ko_stock_prices.csv')

C:\Users\SSAFY\AppData\Local\Temp\ipykernel_3824\220647476.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('ko_stock_prices.csv')

In [3]:
df

         code        date    open    high     low   close     volume    change
0        5930  2000-12-13  3500.0  3779.0  3500.0  3780.0  1682889.0       NaN
1        5930  2000-12-14  3619.0  3680.0  3560.0  3620.0  1339386.0 -0.042328
2        5930  2000-12-15  3620.0  3640.0  3480.0  3490.0  1059217.0 -0.035912
3        5930  2000-12-18  3500.0  3590.0  3489.0  3560.0   687058.0  0.020057
4        5930  2000-12-19  3559.0  3570.0  3510.0  3530.0   508982.0 -0.008427
...       ...         ...     ...     ...     ...     ...        ...       ...
4529103  1527  2025-04-03  8340.0  8340.0  8340.0  8340.0        1.0 -0.021127
4529104  1527  2025-04-04  8300.0  8300.0  8300.0  8300.0      201.0 -0.004796
4529105  1527  2025-04-07  8380.0  8380.0  7500.0  7510.0     2725.0 -0.095181
4529106  1527  2025-04-08  7730.0  7730.0  7570.0  7650.0       98.0  0.018642
4529107  1527  2025-04-09  7650.0  7790.0  7650.0  7790.0       89.0  0.018301

[4529108 rows x 8 columns]

In [5]:
df['code'].unique()

array([5930, 660, 373220, 207940, 5380, 5935, 270, 68270, 12450, 35420,
       105560, 329180, 55550, 12330, 42660, 5490, 138040, 28260, 259960,
       35720, 11200, 810, 86790, 32830, 15760, 51910, 96770, 9540, 10130,
       34020, 33780, 17670, 6400, 30200, 10140, 316140, 24110, 66570,
       402340, 64350, 267260, 323410, 3670, 3550, 352820, 18260, 34730,
       47050, 9150, 100, 86280, 326030, 3490, 47810, 443060, 3230, 272210,
       90430, 42700, 10950, 5830, 267250, 88980, 79550, 21240, 180640,
       6800, 5387, 10620, 64400, 32640, 51900, 161390, 10120, 29780,
       271560, 150, 5940, 720, 241560, 16360, 71050, 22100, 34220, 377300,
       28050, 298040, 97950, 1040, 11790, 450080, 9830, 78930, 251270,
       35250, 5385, 36460, 175330, 6260, 307950, 36570, 880, 138930, 4020,
       128940, 11070, 11780, 302440, 39490, 454910, 462870, 278470, 11170,
       26960, 4370, 139480, 12750, 489790, 383220, 17800, 18880, 18670,
       4990, 88350, 31210, 81660, 2380, 30000, 66970, 111770, 52690,
       20560, 1440, 120, 8930, 7660, 282330, 82740, 1450, 23530, 51600,
       192820, 28670, 990, 204320, 12510, 7310, 161890, 2790, 375500,
       3690, 8770, 139130, 5850, 103140, 69620, 42670, 361610, 294870,
       62040, 395400, 6040, 4170, 6280, 80, 6360, 240, 9420, 112610,
       69960, 47040, 1720, 73240, 7070, 9970, 457190, 10060, 7340, 11210,
       5070, 14680, 192080, 20150, 267270, 300720, 3090, 34230, 137310,
       280360, 1800, 185750, 103590, 89860, 330590, 5300, 365550, 3570,
       1120, 9450, 415640, 3030, 17960, 12630, 71970, 5180, 9240, 1740,
       14820, 4490, 85620, 23590, 336260, 815, 298020, 2840, 229640,
       82640, 3540, 4000, 192400, 1530, 4800, 5440, 51915, 39130, 108320,
       268280, 145720, 950210, 1680, 120110, 100090, 79160, 3240, 9410,
       484870, 298050, 6120, 248070, 114090, 30190, 3850, 32350, 181710,
       451800, 214320, 64960, 293940, 353200, 3620, 670, 25540, 100840,
       1570, 3530, 381970, 30610, 640, 6380, 49770, 210, 69260, 285130,
       500, 5250, 84690, 66575, 1430, '001430', '002030', '097230',
       '079900', '057050', '017810', '008730', '00680K', '005610',
       '071320', '016380', '281820', '306200', '005690', '089590',
       '348950', '005420', '003470', 3470, 6650, 16800, 400, 2350, 36530,
       2710, 10780, 155, 453340, 14830, 336370, 344820, 1060, 403550, 70,
       383800, 178920, 241590, 284740, 475150, 271940, 5880, 456040, 2240,
       77970, 7700, 2960, 272450, 145990, 370, 377740, 3920, 3300,
       '003300', '357120', '460860', '091810', '093370', '093050',
       '105630', '075580', '026890', '448730', '034310', '475560',
       '003545', '192650', '090460', '029530', '009900', '170900',
       '00104K', '017940', '097520', '094800', '058650', '195870',
       '183190', '092790', '005810', '017860', '432320', '093230',
       '019170', '003160', '013890', '00088K', '004690', '003280',
       '004700', '090435', '084010', 84010, 3520, 18250, 499790, 1500,
       34120, 27410, 3960, 5389, 60980, 20000, 31430, 6110, 25860, 5090,
       71055, 24720, 33270, 126560, 37270, 249420, 161000, 5390, 339770,
       72710, 5010, 130660, 16590, 200880, 3220, 35150, 900140, 2310,
       15360, 6390, 2320, 9290, 2020, 104700, 1940, 377190, 88260, 322000,
       123890, 7690, 1270, 6060, 2630, 4430, 122900, 11760, 9680, 286940,
       126720, 1790, 34830, 8060, 3000, 10690, 108670, 17390, 490, 1390,
       680, 5720, 1340, 2810, 226320, 9160, 5500, 334890, 92230, 12030,
       29460, 51905, 16610, 3350, 1820, 11930, 6220, 5945, 13360, 33240,
       298690, 480, 96760, 14160, 8970, 13580, 520, 7810, 1130, 58430,
       1200, 2150, 39570, 11500, 430, 540, 37710, 452260, 1630, 1230,
       7460, 25000, 1250, 4360, 53210, 117580, 138490, 4980, 1510, 272550,
       5680, 3120, 16580, 214420, 293480, 44450, 140, 417310, 70960,
       102460, 19680, 213500, 33920, 1780, 7570, 10770, 8350, 101530,
       2900, 4380, 3200, 9580, 320, 3650, 50, 28100, 102260, 95720, 6340,
       271980, 84680, 460850, 404990, 30210, 97955, 18470, 100250, 134380,
       7110, 107590, 35510, 234080, 1460, 2100, 15860, 37560, 95570,
       68290, 71840, 300, 6405, 20, 7160, 8110, 9470, 6490, 4100, 4560,
       3555, 81000, 27970, 3070, 10820, 11000, 400760, 7860, 78520, 2390,
       53690, 298000, 350520, 36420, 7210, 390, 139990, 1750, 11785, 3580,
       462520, 3610, 3547, 8490, 210980, 9155, 90350, 8040, 92200, 4250,
       970, 1020, 3830, 1045, 4080, 5430, 83420, 9270, 4090, 860, 11280,
       4970, 2170, 79430, 16450, 10955, 700, 11330, 487570, 94280, 128820,
       10580, 15230, 6890, 1360, 25820, 15890, 6840, 24090, 450140, 3060,
       3460, 14280, 33180, 12320, 92220, 480370, 214330, 105840, 1520,
       '001520', '136490', '003720', '210540', '015590', '214390',
       '007540', '02826K', '063160', '248170', '003780', '014530',
       '023450', '004710', '317400', '012610', '012600', '00279K',
       '002620', '120030', '012800', '010100', '069460', '093240',
       '014580', '005950', '267850', '006660', 6660, 14710, 2450, 31440,
       2780, 35000, 7280, 16710, 105, 19440, 1080, 12690, 11150, 4830,
       3480, 9070, 34590, 33530, 51630, 4140, 17550, 20120, 77500, 89470,
       58850, 2200, 5870, 2700, 363280, 14440, 4770, 44820, 267290,
       396690, 8700, 910, 194370, 2210, 17370, 4540, 17900, 123690,
       264900, 157, 11810, 4310, 4890, 2720, 1380, 2460, 4150, 227840,
       23000, 244920, 2600, 13570, 16740, 10040, 8260, 2990, 163560,
       67830, 129260, 5800, 18500, 6880, 6370, 15020, 47400, 9200, 23800,
       16090, 111380, 32560, 1560, 90080, 14790, 4840, 180, 11390, 590,
       58860, 24900, 7590, 338100, 79980, 5740, 1470, 78000, 5960, 96775,
       6090, 13520, 11700, 10660, 21820, 25750, 1260, 71090, 372910,
       10960, 13700, 111110, 16880, 11300, 36580, 4960, 4870, 31820,
       13870, 102280, 220, 11690, 72130, 7980, 230, 100220, 2140, 4720,
       23350, 91090, 4910, 890, 155660, 3925, 92440, 357250, 3560, 4450,
       14990, '014990', '011230', '005750', '481850', '004060', '078935',
       '009770', '075180', '001275', '03473K', '003010', '085310',
       '041650', '002760', 2760, 55490, 850, 6805, 465770, 10640, 11420,
       9180, 11090, 92780, 9190, 8600, 21050, 17040, 134790, '134790',
       '000650', '023810', '001620', '378850', '007610', '002795',
       '008870', '33626K', '101140', '008250', '002410', '001550',
       '027740', '069730', '004410', '004920', '058730', '017180',
       '019180', '026940', '118000', '37550L', '120115', '010600',
       '012170', '009320', 9320, 3080, 6740, 725, 2360, 4440, 2920, 19490,
       8420, 2220, 6980, 1210, 5305, 308170, 123700, 2880, 9460, 9810,
       25530, 12280, 357430, 145270, 9835, 13000, 25560, 1290, '001290',
       '006125', '023960', '003465', '446070', '002870', '049800',
       '014130', '109070', '010420', '033250', '005030', '28513K',
       '020760', 20760, 6570, 74610, 5360, 23150, 12160, 2820, 4270,
       24890, 69640, 12200, 3475, 143210, '143210', '002070', '001140',
       '090370', '37550K', '000950', '071950', '024070', '000215',
       '009140', '005820', '003680', '006200', '119650', '33637K',
       '133820', '005320', '002420', '001420', '000760', '001070',
       '001465', '004365', '007120', '044380', '003535', '019685', 19685,
       40, 9310, 2690, 14910, 5110, 4105, 30720, 84695, 84870, 3495, 1685,
       8775, '008775', '019175', '088790', '145210', '33626L', '025620',
       '025890', '015260', '00499K', '084670', '010400', '33637L',
       '152550', '001770', '009440', '108675', '000087', '002355',
       '000075', '204210', '007815', '005257', '001795', '004835',
       '35320K', '002025', '140910', '001067', '008500', '004255',
       '005725', '18064K', '38380K', '000225', '145995', '003075',
       '001065', '004985', '00806K', '006345', '000885', '45014K',
       '26490K', '000545', '000325', '45226K', '001515', '001755',
       '090355', '004545', '000145', '008355', '005745', '007575',
       '014825', '00781K', '36328K', '012205', 12205, 5965, 14285, 11155,
       2995, 227, 2787, 9415, 2785, 4415, 14915, 1525, 1527], dtype=object)

In [9]:


# 'code' 열에서 유니크한 값들 중 특정 값이 있으면 새로운 DataFrame을 만듦
for value_to_check in df['code'].unique(): 
    print(value_to_check)
    new_df = df[df['code'] == value_to_check]
    # 결과 확인
    if new_df is not None:
        print(new_df)
        new_df.to_csv(f'{value_to_check}_stock.csv')
    else:
        print("새로운 DataFrame을 만들지 않았습니다.")

5930
      code        date     open     high      low    close      volume  \
0     5930  2000-12-13   3500.0   3779.0   3500.0   3780.0   1682889.0
1     5930  2000-12-14   3619.0   3680.0   3560.0   3620.0   1339386.0
2     5930  2000-12-15   3620.0   3640.0   3480.0   3490.0   1059217.0
3     5930  2000-12-18   3500.0   3590.0   3489.0   3560.0    687058.0
4     5930  2000-12-19   3559.0   3570.0   3510.0   3530.0    508982.0
...    ...         ...      ...      ...      ...      ...         ...
5995  5930  2025-04-03  56900.0  57800.0  56900.0  57600.0  19508076.0
5996  5930  2025-04-04  56200.0  58200.0  55700.0  56100.0  23527139.0
5997  5930  2025-04-07  53300.0  54100.0  53100.0  53200.0  31998883.0
5998  5930  2025-04-08  55000.0  55300.0  53300.0  53500.0  25532845.0
5999  5930  2025-04-09  53300.0  54300.0  52900.0  53000.0  20425015.0

        change
0          NaN
1    -0.042328
2    -0.035912
3     0.020057
4    -0.008427
...        ...
5995 -0.020408
5996 -0.026042
5997 -0.051693
5998  0.005639
5999 -0.009346

[6000 rows x 8 columns]
660
      code        date      open      high       low     close      volume  \
6000   660  2000-12-13  133678.0  138389.0  129556.0  137407.0  12132600.0
6001   660  2000-12-14  133481.0  134267.0  131911.0  132500.0   8426010.0
6002   660  2000-12-15  129948.0  132500.0  128770.0  128966.0   5965030.0
6003   660  2000-12-18  126219.0  128378.0  123863.0  124255.0   5788140.0
6004   660  2000-12-19  123667.0  124059.0  105804.0  105803.0  16949900.0
...    ...         ...       ...       ...       ...       ...         ...
11995  660  2025-04-03  189600.0  194600.0  188200.0  194600.0   4177747.0
11996  660  2025-04-04  187900.0  189600.0  178400.0  182200.0   9182017.0
11997  660  2025-04-07  168000.0  172800.0  164800.0  164800.0   7879050.0
11998  660  2025-04-08  172000.0  173100.0  168200.0  169500.0   4965171.0
11999  660  2025-04-09  170000.0  170000.0  162700.0  165000.0   5910529.0

         change
6000        NaN
6001  -0.035711
6002  -0.026672
6003  -0.036529
6004  -0.148501
...         ...
11995 -0.016675
11996 -0.063720
11997 -0.095499
11998  0.028519
11999 -0.026549

[6000 rows x 8 columns]
373220
         code        date      open      high       low     close      volume  \
12000  373220  2022-01-27  597000.0  598000.0  450000.0  505000.0  15946992.0
12001  373220  2022-01-28  476000.0  483000.0  445000.0  450000.0   4559773.0
12002  373220  2022-02-03  458000.0  495500.0  441000.0  477000.0   2918435.0
12003  373220  2022-02-04  476500.0  505000.0  476000.0  504000.0   2088996.0
12004  373220  2022-02-07  520000.0  548000.0  511000.0  548000.0   1911176.0
...       ...         ...       ...       ...       ...       ...         ...
12777  373220  2025-04-03  320000.0  323000.0  310500.0  315000.0    388422.0
12778  373220  2025-04-04  311000.0  331000.0  310500.0  329000.0    363443.0
12779  373220  2025-04-07  318000.0  331000.0  316000.0  323000.0    398358.0
12780  373220  2025-04-08  331000.0  333000.0  315000.0  318000.0    394764.0
12781  373220  2025-04-09  317000.0  325000.0  314000.0  314000.0    330125.0

         change
12000       NaN
12001 -0.108911
12002  0.060000
12003  0.056604
12004  0.087302
...         ...
12777 -0.042553
12778  0.044444
12779 -0.018237
12780 -0.015480
12781 -0.012579

[782 rows x 8 columns]
207940
         code        date       open       high        low      close  \
12782  207940  2016-11-10   133420.0   146267.0   124031.0   142315.0
12783  207940  2016-11-11   147750.0   184317.0   140338.0   159610.0
12784  207940  2016-11-14   163068.0   175422.0   163068.0   173446.0
12785  207940  2016-11-15   176905.0   179375.0   160598.0   164057.0
12786  207940  2016-11-16   166527.0   170975.0   161586.0   168010.0
...       ...         ...        ...        ...        ...        ...
14842  207940  2025-04-03  1035000.0  1127000.0  1035000.0  1113000.0
14843  207940  2025-04-04  1098000.0  1110000.0  1060000.0  1069000.0
14844  207940  2025-04-07  1015000.0  1025000.0  1003000.0  1008000.0
14845  207940  2025-04-08  1020000.0  1033000.0  1001000.0  1004000.0
14846  207940  2025-04-09   998000.0  1008000.0   987000.0   992000.0

          volume    change
12782  7264033.0       NaN
12783  8236940.0  0.121526
12784  3012433.0  0.086686
12785  2623655.0 -0.054132
12786  1680645.0  0.024095
...          ...       ...
14842   141538.0  0.060000
14843   101519.0 -0.039533
14844   112082.0 -0.057063
14845   140449.0 -0.003968
14846   101876.0 -0.011952

[2065 rows x 8 columns]
5380
       code        date      open      high       low     close     volume  \
14847  5380  2000-12-13   12550.0   12950.0   12500.0   12800.0  1069360.0
14848  5380  2000-12-14   12650.0   13050.0   12650.0   12700.0  1175470.0
14849  5380  2000-12-15   12500.0   12700.0   12450.0   12500.0   680020.0
14850  5380  2000-12-18   12250.0   12650.0   12200.0   12500.0  3249750.0
14851  5380  2000-12-19   12500.0   12500.0   11800.0   11800.0   677140.0
...     ...         ...       ...       ...       ...       ...        ...
20842  5380  2025-04-03  191000.0  194500.0  189100.0  193800.0   954824.0
20843  5380  2025-04-04  191300.0  196500.0  189600.0  191800.0   810211.0
20844  5380  2025-04-07  184700.0  185300.0  178900.0  179100.0  1244441.0
20845  5380  2025-04-08  181400.0  183800.0  177500.0  179200.0  1082825.0
20846  5380  2025-04-09  177500.0  180900.0  177300.0  178000.0   689621.0

         change
14847       NaN
14848 -0.007812
14849 -0.015748
14850  0.000000
14851 -0.056000
...         ...
20842 -0.012736
20843 -0.010320
20844 -0.066215
20845  0.000558
20846 -0.006696

[6000 rows x 8 columns]
5935
       code        date     open     high      low    close     volume  \
20847  5935  2000-12-13   1530.0   1598.0   1510.0   1596.0   381532.0
20848  5935  2000-12-14   1516.0   1562.0   1516.0   1550.0   190910.0
20849  5935  2000-12-15   1540.0   1550.0   1522.0   1530.0   185154.0
20850  5935  2000-12-18   1528.0   1578.0   1520.0   1576.0   206678.0
20851  5935  2000-12-19   1570.0   1578.0   1536.0   1540.0   154167.0
...     ...         ...      ...      ...      ...      ...        ...
26842  5935  2025-04-03  46600.0  47400.0  46600.0  47000.0  1257576.0
26843  5935  2025-04-04  46400.0  47700.0  45850.0  46500.0  1593250.0
26844  5935  2025-04-07  44600.0  45100.0  44050.0  44050.0  1962905.0
26845  5935  2025-04-08  45800.0  45800.0  44250.0  44600.0  1479775.0
26846  5935  2025-04-09  44000.0  45100.0  44000.0  44300.0  1011387.0

         change
20847       NaN
20848 -0.028822
20849 -0.012903
20850  0.030065
20851 -0.022843
...         ...
26842 -0.015707
26843 -0.010638
26844 -0.052688
26845  0.012486
26846 -0.006726

[6000 rows x 8 columns]
270
      code        date     open     high      low    close     volume  \
26847  270  2000-12-13   7150.0   7430.0   6900.0   7290.0  2704330.0
26848  270  2000-12-14   7270.0   7270.0   6710.0   6710.0  3359800.0
26849  270  2000-12-15   6720.0   6930.0   6720.0   6900.0   763020.0
26850  270  2000-12-18   6900.0   7000.0   6610.0   6610.0  2466860.0
26851  270  2000-12-19   6610.0   6750.0   6350.0   6590.0  2645720.0
...    ...         ...      ...      ...      ...      ...        ...
32842  270  2025-04-03  89200.0  91400.0  88400.0  90800.0  1054819.0
32843  270  2025-04-04  89500.0  91800.0  88700.0  89700.0   947048.0
32844  270  2025-04-07  86100.0  87100.0  84100.0  84600.0  1066394.0
32845  270  2025-04-08  85500.0  86600.0  84200.0  84300.0   952615.0
32846  270  2025-04-09  83900.0  84200.0  82800.0  83800.0   996604.0

         change
26847       NaN
26848 -0.079561
26849  0.028316
26850 -0.042029
26851 -0.003026
...         ...
32842 -0.014115
32843 -0.012115
32844 -0.056856
32845 -0.003546
32846 -0.005931

[6000 rows x 8 columns]
68270
        code        date      open      high       low     close    volume  \
32847  68270  2005-07-19    2235.0    2569.0    2171.0    2572.0  746815.0
32848  68270  2005-07-20    2567.0    2567.0    2186.0    2188.0  632493.0
32849  68270  2005-07-21    2153.0    2197.0    1911.0    1917.0  273363.0
32850  68270  2005-07-22    1951.0    1951.0    1845.0    1864.0  104627.0
32851  68270  2005-07-25    1832.0    1984.0    1832.0    1887.0   91331.0
...      ...         ...       ...       ...       ...       ...       ...
37713  68270  2025-04-03  165800.0  174000.0  165700.0  173500.0  594307.0
37714  68270  2025-04-04  172900.0  174600.0  170500.0  173900.0  450814.0
37715  68270  2025-04-07  167600.0  167800.0  161900.0  164400.0  730805.0
37716  68270  2025-04-08  166400.0  166900.0  162900.0  163100.0  594362.0
37717  68270  2025-04-09  161500.0  163000.0  152900.0  154500.0  902413.0

         change
32847       NaN
32848 -0.149300
32849 -0.123857
32850 -0.027647
32851  0.012339
...         ...
37713  0.022392
37714  0.002305
37715 -0.054629
37716 -0.007908
37717 -0.052728

[4871 rows x 8 columns]
12450
        code        date      open      high       low     close    volume  \
37718  12450  2000-12-13    4588.0    4754.0    4583.0    4754.0  800790.0
37719  12450  2000-12-14    4643.0    4754.0    4621.0    4660.0  691280.0
37720  12450  2000-12-15    4625.0    4681.0    4565.0    4666.0  492675.0
37721  12450  2000-12-18    4599.0    4698.0    4599.0    4683.0  334243.0
37722  12450  2000-12-19    4681.0    4681.0    4526.0    4572.0  503317.0
...      ...         ...       ...       ...       ...       ...       ...
43713  12450  2025-04-03  652000.0  710000.0  650000.0  697000.0  427177.0
43714  12450  2025-04-04  705000.0  720000.0  675000.0  702000.0  422746.0
43715  12450  2025-04-07  683000.0  684000.0  636000.0  642000.0  412797.0
43716  12450  2025-04-08  686000.0  705000.0  670000.0  698000.0  558169.0
43717  12450  2025-04-09  717000.0  717000.0  673000.0  691000.0  411172.0

         change
37718       NaN
37719 -0.019773
37720  0.001288
37721  0.003643
37722 -0.023703
...         ...
43713  0.051282
43714  0.007174
43715 -0.085470
43716  0.087227
43717 -0.010029

[6000 rows x 8 columns]
35420
        code        date      open      high       low     close     volume  \
43718  35420  2002-10-29    2312.0    2312.0    2312.0    2312.0    20549.0
43719  35420  2002-10-30    2587.0    2587.0    2558.0    2588.0   853638.0
43720  35420  2002-10-31    2626.0    2689.0    2398.0    2459.0  1320880.0
43721  35420  2002-11-01    2520.0    2599.0    2215.0    2305.0   750761.0
43722  35420  2002-11-04    2285.0    2300.0    2135.0    2191.0   692165.0
...      ...         ...       ...       ...       ...       ...        ...
49257  35420  2025-04-03  190900.0  199600.0  190800.0  198600.0   577896.0
49258  35420  2025-04-04  196700.0  202500.0  194100.0  197800.0   672143.0
49259  35420  2025-04-07  192400.0  195200.0  189300.0  191800.0   597627.0
49260  35420  2025-04-08  192100.0  193000.0  179200.0  179600.0  1366603.0
49261  35420  2025-04-09  179000.0  181300.0  176200.0  176900.0   621304.0

         change
43718       NaN
43719  0.119377
43720 -0.049845
43721 -0.062627
43722 -0.049458
...         ...
49257  0.015337
49258 -0.004028
49259 -0.030334
49260 -0.063608
49261 -0.015033

[5544 rows x 8 columns]
105560
         code        date     open     high      low    close      volume  \
49262  105560  2008-10-10  47063.0  47063.0  40026.0  45940.0  13011873.0
49263  105560  2008-10-13  47063.0  50338.0  45500.0  49556.0   3180584.0
49264  105560  2008-10-14  52781.0  54736.0  50631.0  51902.0   3957562.0
49265  105560  2008-10-15  49067.0  50142.0  48578.0  49850.0   2852067.0
49266  105560  2008-10-16  44620.0  44913.0  42421.0  42421.0   3941080.0
...       ...         ...      ...      ...      ...      ...         ...
53329  105560  2025-04-03  77300.0  78300.0  76800.0  77100.0   1550963.0
53330  105560  2025-04-04  75700.0  78300.0  75700.0  77700.0   1379580.0
53331  105560  2025-04-07  74300.0  74400.0  71800.0  72300.0   1936293.0
53332  105560  2025-04-08  71700.0  72500.0  69500.0  70500.0   2165054.0
53333  105560  2025-04-09  70500.0  71200.0  69300.0  70900.0   1189462.0

         change
49262       NaN
49263  0.078711
49264  0.047340
49265 -0.039536
49266 -0.149027
...         ...
53329 -0.042236
53330  0.007782
53331 -0.069498
53332 -0.024896
53333  0.005674

[4072 rows x 8 columns]
329180
         code        date      open      high       low     close      volume  \
53334  329180  2021-09-17  111000.0  135000.0   91000.0  111500.0  17373529.0
53335  329180  2021-09-23  112000.0  113000.0   99000.0   99100.0   2914293.0
53336  329180  2021-09-24  100000.0  102000.0   95500.0   99200.0   2262592.0
53337  329180  2021-09-27   98300.0   99400.0   96500.0   97000.0    672212.0
53338  329180  2021-09-28   98000.0  103000.0   97000.0  100000.0   1037427.0
...       ...         ...       ...       ...       ...       ...         ...
54199  329180  2025-04-03  286500.0  295500.0  286000.0  295500.0    184291.0
54200  329180  2025-04-04  291500.0  309000.0  291500.0  300000.0    341845.0
54201  329180  2025-04-07  284000.0  289000.0  275500.0  275500.0    333671.0
54202  329180  2025-04-08  285500.0  295500.0  285500.0  294500.0    288828.0
54203  329180  2025-04-09  301500.0  303000.0  287500.0  293500.0    405588.0

         change
53334       NaN
53335 -0.111211
53336  0.001009
53337 -0.022177
53338  0.030928
...         ...
54199  0.015464
54200  0.015228
54201 -0.081667
54202  0.068966
54203 -0.003396

[870 rows x 8 columns]
55550
        code        date     open     high      low    close     volume  \
54204  55550  2001-09-10  10797.0  11324.0   9885.0  10894.0  1254910.0
54205  55550  2001-09-11  11037.0  11277.0  10894.0  11181.0  1239210.0
54206  55550  2001-09-12   9549.0  10509.0   9549.0   9694.0  1468150.0
54207  55550  2001-09-13  10173.0  10749.0  10029.0  10366.0  1916800.0
54208  55550  2001-09-14  10077.0  10317.0   9549.0   9742.0  1323690.0
...      ...         ...      ...      ...      ...      ...        ...
60020  55550  2025-04-03  47050.0  47650.0  46700.0  47550.0  1292227.0
60021  55550  2025-04-04  46900.0  47550.0  46300.0  47050.0  1351789.0
60022  55550  2025-04-07  45000.0  45600.0  44150.0  45050.0  1867826.0
60023  55550  2025-04-08  45550.0  45550.0  43750.0  43850.0  1847161.0
60024  55550  2025-04-09  43550.0  44000.0  42500.0  43600.0  1647012.0

         change
54204       NaN
54205  0.026345
54206 -0.132993
54207  0.069321
54208 -0.060197
...         ...
60020 -0.023614
60021 -0.010515
60022 -0.042508
60023 -0.026637
60024 -0.005701

[5821 rows x 8 columns]
12330
        code        date      open      high       low     close    volume  \
60025  12330  2000-12-13    4680.0    4800.0    4620.0    4775.0  295790.0
60026  12330  2000-12-14    4665.0    4810.0    4665.0    4770.0  345620.0
60027  12330  2000-12-15    4770.0    4850.0    4700.0    4780.0  272240.0
60028  12330  2000-12-18    4780.0    4845.0    4780.0    4780.0  330960.0
60029  12330  2000-12-19    4760.0    4800.0    4550.0    4600.0  454380.0
...      ...         ...       ...       ...       ...       ...       ...
66020  12330  2025-04-03  253500.0  260000.0  252500.0  260000.0  243145.0
66021  12330  2025-04-04  258500.0  263000.0  255500.0  259000.0  154827.0
66022  12330  2025-04-07  248500.0  251500.0  243000.0  248500.0  170953.0
66023  12330  2025-04-08  250500.0  251000.0  235500.0  236500.0  236443.0
66024  12330  2025-04-09  237500.0  239500.0  233500.0  235000.0  154384.0

         change
60025       NaN
60026 -0.001047
60027  0.002096
60028  0.000000
60029 -0.037657
...         ...
66020 -0.018868
66021 -0.003846
66022 -0.040541
66023 -0.048290
66024 -0.006342

[6000 rows x 8 columns]
42660
        code        date     open     high      low    close     volume  \
66025  42660  2001-02-02   1553.0   1787.0   1553.0   1787.0  9723154.0
66026  42660  2001-02-05   1860.0   1864.0   1562.0   1776.0  7686628.0
66027  42660  2001-02-06   2042.0   2042.0   1869.0   1994.0  7714656.0
66028  42660  2001-02-07   1975.0   1975.0   1802.0   1807.0  3855729.0
66029  42660  2001-02-08   1687.0   1812.0   1687.0   1719.0  4004511.0
...      ...         ...      ...      ...      ...      ...        ...
71991  42660  2025-04-03  68600.0  72000.0  68200.0  71600.0  1896496.0
71992  42660  2025-04-04  71200.0  72300.0  66900.0  69300.0  3616908.0
71993  42660  2025-04-07  66000.0  66100.0  62350.0  62500.0  3000005.0
71994  42660  2025-04-08  65600.0  68000.0  65000.0  67700.0  2668105.0
71995  42660  2025-04-09  70900.0  70900.0  67500.0  68600.0  2926001.0

         change
66025       NaN
66026 -0.006156
66027  0.122748
66028 -0.093781
66029 -0.048700
...         ...
71991  0.028736
71992 -0.032123
71993 -0.098124
71994  0.083200
71995  0.013294

[5971 rows x 8 columns]
5490
       code        date      open      high       low     close    volume  \
71996  5490  2000-12-13   78600.0   82100.0   78600.0   81000.0  512953.0
71997  5490  2000-12-14   81000.0   81600.0   80200.0   80700.0  524741.0
71998  5490  2000-12-15   80700.0   80800.0   79600.0   80500.0  339806.0
71999  5490  2000-12-18   80500.0   81100.0   80300.0   80600.0  358560.0
72000  5490  2000-12-19   80600.0   80600.0   78500.0   78500.0  215751.0
...     ...         ...       ...       ...       ...       ...       ...
77991  5490  2025-04-03  263000.0  272500.0  261500.0  271000.0  368358.0
77992  5490  2025-04-04  267000.0  278000.0  265500.0  273000.0  461911.0
77993  5490  2025-04-07  260000.0  261500.0  253500.0  255000.0  510440.0
77994  5490  2025-04-08  260000.0  263000.0  250500.0  251500.0  532973.0
77995  5490  2025-04-09  249500.0  259000.0  246000.0  249500.0  498399.0

         change
71996       NaN
71997 -0.003704
71998 -0.002478
71999  0.001242
72000 -0.026055
...         ...
77991 -0.003676
77992  0.007380
77993 -0.065934
77994 -0.013725
77995 -0.007952

[6000 rows x 8 columns]
138040
         code        date      open      high       low     close      volume  \
77996  138040  2011-05-13    6161.0    6161.0    5241.0    5242.0    428994.0
77997  138040  2011-05-16    4464.0    4464.0    4464.0    4465.0    487412.0
77998  138040  2011-05-17    3938.0    4056.0    3796.0    3796.0  12268654.0
77999  138040  2011-05-18    3881.0    3895.0    3706.0    3730.0   6188170.0
78000  138040  2011-05-19    3739.0    3763.0    3194.0    3280.0   6181312.0
...       ...         ...       ...       ...       ...       ...         ...
81414  138040  2025-04-03  118100.0  119800.0  117800.0  119100.0    265016.0
81415  138040  2025-04-04  119000.0  119700.0  117000.0  118400.0    216514.0
81416  138040  2025-04-07  114000.0  114700.0  108600.0  111700.0    490544.0
81417  138040  2025-04-08  112600.0  114300.0  110200.0  111000.0    211349.0
81418  138040  2025-04-09  109300.0  110500.0  107100.0  107800.0    359348.0

         change
77996       NaN
77997 -0.148226
77998 -0.149832
77999 -0.017387
78000 -0.120643
...         ...
81414 -0.016515
81415 -0.005877
81416 -0.056588
81417 -0.006267
81418 -0.028829

[3423 rows x 8 columns]
28260
        code        date      open      high       low     close      volume  \
81419  28260  2014-12-18  106000.0  116000.0   99200.0  113000.0  12845103.0
81420  28260  2014-12-19  118000.0  129500.0  117500.0  129500.0   4551888.0
81421  28260  2014-12-22  135000.0  145500.0  130500.0  134500.0   4401710.0
81422  28260  2014-12-23  132000.0  137500.0  127000.0  135000.0   2873094.0
81423  28260  2014-12-24  135500.0  139000.0  132000.0  133000.0   1403337.0
...      ...         ...       ...       ...       ...       ...         ...
83945  28260  2025-04-03  116100.0  118100.0  115500.0  118100.0    239733.0
83946  28260  2025-04-04  116700.0  119000.0  115300.0  117400.0    269509.0
83947  28260  2025-04-07  112800.0  113600.0  110700.0  112200.0    348099.0
83948  28260  2025-04-08  113400.0  114300.0  111200.0  111400.0    236919.0

In [2]:
df.columns()

NameError: name 'df' is not defined